import { IBObject } from './object.model';
import { IBCard } from './ccard.model';
import { IBAddress } from './address.model';
import { IBCoupon } from './coupon.model';
import { IBOrder } from './order.model';
export declare class IBUser extends IBObject {
    email: string;
    fName: string;
    lName: string;
    gender: string;
    birthday: string;
    cpf: string;
    phone: string;
    photo: string;
    cards: Array<IBCard>;
    addresses: Array<IBAddress>;
    coupons: Array<IBCoupon>;
    orders: Array<IBOrder>;
    recentOrders: number;
    validateEmail: Function;
    reverseBirthday: Function;
    constructor();
    setData(data: object): void;
    setOrders(orders: Array<object>): void;
    setCards(cards: Array<object>): void;
    setAddresses(addresses: Array<object>): void;
    setCoupons(coupons: Array<object>): void;
    getPhoto(): string;
    registerUserDocument(password?: string, facebookId?: string): object;
    saveUserDocument(): object;
    insertAddress(address: IBAddress): void;
    removeAddress(address: IBAddress): void;
    insertCCard(ccard: IBCard): void;
    removeCCard(ccard: IBCard): void;
    getAddress(addressId: string): IBAddress;
    getCard(cardId: string): IBCard;
    getCoupon(code: string): IBCoupon;
    getOrder(code: string): IBOrder;
}
